import "./globals.css";
import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import { cn } from "@/lib/utils";
import { LayoutProps } from "@/@types/common";
import { Provider } from "@/providers";
import { NavbarMobile } from "@/app/components/organisms/navbar/navbar-mobile";
import { Navbar } from "@/app/components/organisms/navbar/navbar";
import { NavbarProvider } from "@/providers/navbar/navbar";
import { NextIntlClientProvider, useMessages } from "next-intl";

export const spaceMono = Space_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-space-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<LayoutProps>) {
  const messages = useMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          spaceMono.variable
        )}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Provider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavbarProvider>
              <Navbar locale={locale} />
              <NavbarMobile locale={locale} />
            </NavbarProvider>
            <main className="space-mono p-14">{children}</main>
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
